### ISSUE TITLE
Subir fichero Dockerfile

### ISSUE THREAD

**Issue by acasadoquijada** [acasadoquijada/MyStudentBot#20]

**Comment by grivasgervilla** [comment]
He podido descargar tu imagen desde Dockerhub y crear un contenedor a partir de ella sin problemas. Además he probado a ejecutar algún comando en él:
![imagen](https://cloud.githubusercontent.com/assets/7707062/21753019/7d47ef22-d5e3-11e6-832e-a2b50bb7619d.png)
